AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sas-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  SasBackendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sas-backendni
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::sas_backend.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Function:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  SasBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for SasBackend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/DebuggingExample/"

  SasBackendFunction:
    Description: "Debugging Example Lambda Function ARN"
    Value: !GetAtt SasBackendFunction.Arn

  SasBackendFunctionIamRole:
    Description: "Implicit IAM Role created for Debugging Example function"
    Value: !GetAtt SasBackendFunctionRole.Arn