AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sas-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetItems
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::function.EntryPoints.GetItemsEntryPoint::HandleAsync
      Runtime: dotnetcore2.1
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /items
            Method: Get
  GetItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetItemById
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::function.EntryPoints.GetItemEntryPoint::HandleAsync
      Runtime: dotnetcore2.1
      Events:
        GetItemById:
          Type: Api
          Properties:
            Path: /items/id/{id}
            Method: Get
  GetLoansByStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetLoansByStatus
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::function.EntryPoints.GetLoansByStatus::HandleAsync
      Runtime: dotnetcore2.1
      Events:
        GetLoansByStatus:
          Type: Api
          Properties:
            Path: /loans/status/{status}
            Method: Get
  GetLoanByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetLoanById
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::function.EntryPoints.GetLoanById::HandleAsync
      Runtime: dotnetcore2.1
      Events:
        GetLoanById:
          Type: Api
          Properties:
            Path: /loans/id/{id}
            Method: Get
  PostTestLoansFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostTestLoans
      CodeUri: "function/bin/Release/netcoreapp2.1/publish"
      Handler: function::function.EntryPoints.CreateLoansEntryPoint::HandleAsync
      Runtime: dotnetcore2.1
      Events:
        GetLoanById:
          Type: Api
          Properties:
            Path: /loans/all
            Method: Post

Outputs:
  SasBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for SasBackend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
